version: "3"
services:
  nginx:
    ports:
      - "80:80"
  multer-upload:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    command: node index.js
